language: python
python:
    - "2.5"
    - "2.6"
    - "2.7"
    - "3.1"
    - "3.2"
    - 'pypy'

install:
  - "pip install . --use-mirrors"

branches:
  only:
    - master
    - test  
  
script: py.test

notifications:
    email:
        on_success: change
        on_failure: change